import type { FileKind, PrivacyReportData } from "@/types";

export const MAX_FILE_SIZE_BYTES = 20 * 1024 * 1024;

const supportedExtensions = ["pdf", "png", "jpg", "jpeg", "webp"] as const;

const imageMimeTypes = new Set([
  "image/png",
  "image/jpeg",
  "image/jpg",
  "image/webp",
]);

export function getFileExtension(fileName: string) {
  const parts = fileName.split(".");
  return parts.length > 1 ? parts.pop()?.toLowerCase() ?? "" : "";
}

export function getFileKind(file: File): FileKind | null {
  if (file.type === "application/pdf" || getFileExtension(file.name) === "pdf") {
    return "pdf";
  }

  if (imageMimeTypes.has(file.type) || supportedExtensions.includes(getFileExtension(file.name) as (typeof supportedExtensions)[number])) {
    return "image";
  }

  return null;
}

export function validateFile(file: File) {
  const kind = getFileKind(file);

  if (!kind) {
    return {
      kind: null,
      error: "Unsupported file type. Upload a PDF, PNG, JPG, JPEG, or WEBP file.",
    };
  }

  if (file.size > MAX_FILE_SIZE_BYTES) {
    return {
      kind: null,
      error: "File is too large. The maximum supported size is 20MB.",
    };
  }

  return { kind, error: null };
}

export function formatFileSize(bytes: number) {
  if (bytes < 1024) {
    return `${bytes} B`;
  }

  const units = ["KB", "MB", "GB"];
  let size = bytes / 1024;
  let unitIndex = 0;

  while (size >= 1024 && unitIndex < units.length - 1) {
    size /= 1024;
    unitIndex += 1;
  }

  return `${size.toFixed(size >= 10 ? 1 : 2)} ${units[unitIndex]}`;
}

export function buildOutputName(fileName: string, suffix: string, extension?: string) {
  const lastDot = fileName.lastIndexOf(".");
  const baseName = lastDot >= 0 ? fileName.slice(0, lastDot) : fileName;
  const currentExtension = lastDot >= 0 ? fileName.slice(lastDot + 1) : "";
  const nextExtension = extension ?? currentExtension;
  return `${baseName}${suffix}.${nextExtension}`;
}

export function getFriendlyFileType(file: File) {
  const extension = getFileExtension(file.name).toUpperCase();
  if (file.type === "application/pdf" || extension === "PDF") {
    return "PDF";
  }

  return extension || file.type || "Unknown";
}

export function triggerDownload(url: string, fileName: string) {
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
}

export function buildPrivacyReportText(report: PrivacyReportData) {
  const lines = [
    "ShareSafe Privacy Report",
    "========================",
    `File name: ${report.fileName}`,
    `File type: ${report.fileType}`,
    `Original size: ${formatFileSize(report.originalSize)}`,
    `Final size: ${report.finalSize ? formatFileSize(report.finalSize) : "Not generated yet"}`,
    "",
    "Detected sensitive items:",
  ];

  if (report.detections.length === 0) {
    lines.push("None detected.");
  } else {
    report.detections.forEach((item) => {
      lines.push(`- ${item.type}: ${item.value} (${item.count})`);
    });
  }

  lines.push("", "Actions applied:");

  if (report.actionsApplied.length === 0) {
    lines.push("None yet.");
  } else {
    report.actionsApplied.forEach((action) => lines.push(`- ${action}`));
  }

  if (report.notes.length > 0) {
    lines.push("", "Notes:");
    report.notes.forEach((note) => lines.push(`- ${note}`));
  }

  lines.push("", "Generated by ShareSafe.");
  return lines.join("\n");
}
